version: '3'

services:
  azlyrics:
    container_name: azlyrics
    build:
        context: .
        dockerfile: docker/Dockerfile
    volumes:
      - ./src:/usr/src
    ports:
      - "5001:5001"
    stdin_open: true
    restart: always
    tty: true
    environment:
        # PROJECT SETTINGS
        - ENVIRONMENT=local
        - PORT=5001
        - HOST=0.0.0.0
        - DEBUG=True
        # DATABASE
        - DATABASE_URI=postgresql://user:password@lyrics_db/lyric
        # AZLYRICS
        - AZLYRICS_URL=https://www.azlyrics.com/{}.html
        - AZLYRICS_ARTIST=https://www.azlyrics.com/{}/{}.html
        - AZLYRICS_SEARCH=https://search.azlyrics.com/search.php
        - AZLYRICS_X_PARAM=db229f8201a5bafca20d77d7ef3004c1c4352da6096bf2cc24af214c8e6a02c4
        - ALBUMS_MAX_LIMIT=5
        - SONGS_MAX_LIMIT=5
        - ARTISTS_MAX_LIMIT=5

  lyrics_db:
    container_name: lyrics_db
    build:
      dockerfile: docker/Database.Dockerfile
    restart: always
    ports:
      - "5050:5432"
    volumes:
          - ~/Documents/lyrics_db/.pgdata:/var/lib/postgresql/data
    environment:
        - POSTGRES_USER=user
        - POSTGRES_PASSWORD=password
        - POSTGRES_DB=lyric
